name: abstract_router_example
description: Demonstrates how to use the abstract_router module.

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:

dev_dependencies:
  abstract_router:
    path: ../
