
language: dart

dart:
# Install the latest stable release
  - stable

before_install:
  - export DISPLAY=:99.0
  - export PUB_HOSTED_URL=https://pub.flutter-io.cn
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - test: --exclude-tags no-xvfb
  - test: --tags no-xvfb
  - dartanalyzer: --fatal-warnings lib
install_dartium: true
xvfb: false
