name: abstract_router
description: An abstract routing implementation that provides a low-level implementation of a fast, efficient, and practical routing system for any scenario that uses routing.
version: 1.0.0
homepage: https://github.com/dart-router/abstract-router
author: 老三 <123572970@qq.com>

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.5.1
  test_coverage: ^0.2.0
  pedantic: '1.1.0'